-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.7.30-log - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             11.0.0.5919
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for words
CREATE DATABASE IF NOT EXISTS `fypcurve` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `fypcurve`;

-- Dumping data for table words.cet: ~4,447 rows (approximately)
/*!40000 ALTER TABLE `cet` DISABLE KEYS */;
INSERT IGNORE INTO `en_words` (`id`, `english`, `chinese`, `sent`, `level`) VALUES
	(1, '﻿pasture', 'vt.丢弃；放弃，抛弃', '/‘bækwəd/', '4'),
	(2, 'backward', 'a.向后的；倒的ad.倒', '/‘sΛmit/', '6'),
	(3, 'summon', 'vt.召唤；鼓起(勇气)', '/‘sΛmәn/', '6'),
	(4, 'bathe', 'vt.给…洗澡；弄湿', '/beið/', '6'),
	(5, 'superiority', 'n.优越(性)，优势', '/sju:pәri’ɔriti/', '6'),
	(6, 'biography', 'n. 传记', '/bai’ɔgrәfi/', '6'),
	(7, 'supervise', 'vt.&vi.监督，监视', '/‘sju:pәvaiz/', '6'),
	(8, 'supplementary', 'a.补足/补充/追加的', '/sΛpli’mentәri/', '6'),
	(9, 'bureaucracy', 'n.官僚主义；官僚机构', '/bjuә’rɔkrәsi/', '6'),
	(10, 'surge', 'n.vt. 激增,奔放,汹涌,澎湃', '/sә:dʒ/', '6'),
	(11, 'correspondence', 'n.通信；符合；对应', '/kɔris’pɔndәns/', '6'),
	(12, 'surpass', 'vt.超过，超越，胜过', '/sә:’pa:s/', '6'),
	(13, 'surplus', 'n.过剩，剩余(物资)', '/‘sә:plәs/', '6'),
	(14, 'cradle', 'n.摇篮，发源地', '/‘kreidl/', '6'),
	(15, 'susceptible', 'a. 易受影响的,易感动的', '/sә’septәbl/', '6'),
	(16, 'bribe', 'n.贿赂 vt.向…行贿', '/braib/', '6'),
	(17, 'brisk', 'a.活泼的；清新的', '/brisk/', '6'),
	(18, 'brittle', 'a.脆的；易损坏的', '/‘britl/', '6'),
	(19, 'bronze', 'n.青铜色', '/brɔnz/', '6'),
	(20, 'brood', 'n.同窝幼鸟 vt.孵(蛋)', '/bru:d/', '6'),
	(21, 'symposium', 'n.酒会；座谈会', '/sim’pәuzjәm/', '6'),
	(22, 'symptom', 'n.症状，征候，征兆', '/‘simptәm/', '6'),
	(23, 'synthesis', 'n.合成；综合，综合物', '/‘sinθisis/', '6'),
	(24, 'tablet', 'n.碑，匾；药片', '/‘tæblit/', '6'),
	(25, 'tackle', 'vt.解决，对付 n.用具', '/‘tækl/', '6'),
	(26, 'tactics', 'n.策略；战术，兵法', '/‘tæktiks/', '6'),
	(27, 'tangle', 'vt.使缠结，使纠缠', '/‘tæŋgl/', '6'),
	(28, 'tar', 'n.柏油，焦油', '/ta:/', '6'),
	(29, 'tariff', 'n.关税,价格表,收费表 vt. 课以关税', '/‘tærif/', '6'),
	(30, 'tease', 'vt.逗乐，戏弄；强求', '/ti:z/', '6'),
	(31, 'temperament', 'n. 气质,性质,性情', '/‘tempәrәmәnt/', '6'),
	(32, 'bias', 'n. 偏见,偏袒,斜线 vt.使有偏见', '/‘baiәs/', '6'),
	(33, 'bibliography', 'n. 参考书目', '/bibli’ɔgrәfi/', '6'),
	(34, 'bid', 'n. 出价vt.vi. 命令,吩咐,投标', '/bid/', '6'),
	(35, 'basement', 'n.地下室；地窖；底层', '/‘beismәnt/', '6'),
	(36, 'bizarre', 'a. 奇异的', '/bi’za:/', '6'),
	(37, 'blaze', 'n.火；闪光 vi.燃烧', '/bleiz/', '6'),
	(38, 'bleak', 'a. 萧瑟的,苍白的,荒凉的', '/bli:k/', '6'),
	(39, 'terrify', 'vt.使恐怖，使惊吓', '/‘terifai/', '6'),
	(40, 'testify', 'v.证明，证实，作证', '/‘testifai/', '6'),
	(41, 'testimony', 'n. 证言,证据,声明', '/‘testimәni/', '6'),
	(42, 'texture', 'n. 质地，纹理', '/‘tekstʃә/', '6'),
	(43, 'thanksgiving', 'n.感恩节', '/‘θæŋksgiviŋ/', '6'),
	(44, 'theft', 'n.盗窃，偷窃(行为)', '/θeft/', '6'),
	(45, 'theme', 'n.题目；词干；主旋律', '/θi:m/', '6'),
	(46, 'therapy', 'n. 治疗', '/‘θerәpi/', '6'),
	(47, 'thereafter', 'ad.此后，以后', '/ðɛә’ra:ftә/', '6'),
	(48, 'thermal', 'a.热的；温泉的', '/‘ðә:mәl/', '6'),
	(49, 'thesis', 'n.论题，论点；论文', '/‘θi:sis/', '6'),
	(50, 'thirst', 'n.渴，口渴；渴望', '/θә:st/', '6'),
	(51, 'thorn', 'n.刺，棘；荆棘；蒺藜', '/θɔ:n/', '6'),
	(52, 'threshold', 'n.门槛；入门，开端', '/‘θreʃhәuld/', '6'),
	(53, 'brood', 'n.同窝幼鸟 vt.孵(蛋)', '/bru:d/', '6'),
	(54, 'bruise', 'n.青肿，伤痕；擦伤', '/bru:z/', '6'),
	(55, 'brutal', 'a. 残忍的,野蛮的,不讲理的', '/‘bru:tl/', '6'),
	(56, 'bud', 'n.芽，萌芽；蓓蕾', '/bΛd/', '6'),
	(57, 'budget', 'n.预算，预算案', '/‘bΛdʒit/', '6'),
	(58, 'buffer', 'n. 缓冲,缓冲区 vt. 缓冲', '/‘bΛfә/', '6'),
	(59, 'bug', 'n.虫子；臭虫', '/bΛg/', '6'),
	(60, 'bull', 'n.买空的证券投机商', '/bul/', '6'),
	(61, 'bulletin', 'n.告示，公告，公报', '/‘bulitin/', '6'),
	(62, 'toss', 'vi.翻来复去', '/tɔs/', '6'),
	(63, 'tow', 'vt.&n.拖引，牵引', '/tәu/', '6'),
	(64, 'tract', 'n.传单,小册子,大片(土地或森林)', '/‘trækt/', '6'),
	(65, 'tragic', 'a.悲剧性的，悲惨的', '/‘trædʒik/', '6'),
	(66, 'trait', 'n. 显著特点，特性', '/treit/', '6'),
	(67, 'transaction', 'n.处理；交易；和解', '/træn’zækʃәn/', '6'),
	(68, 'transcend', 'vt. 超越,胜过', '/træn’send/', '6'),
	(69, 'transient', 'a.短暂的,转瞬即逝的,临时的,暂住的', '/‘trænziәnt/', '6'),
	(70, 'transit', 'n.运输 a.中转的，过境的', '/‘trænsit/', '6'),
	(71, 'transition', 'n.转变，变迁；过渡', '/træn’siʃәn/', '6'),
	(72, 'transplant', 'vt.&vi.移植，移种', '/træns’pla:nt/', '6'),
	(73, 'traverse', 'vt.横越，横切，横断', '/‘trævә:s/', '6'),
	(74, 'trench', 'n.深沟；壕沟，战壕', '/trentʃ/', '6'),
	(75, 'tribe', 'n.部落，宗族', '/traib/', '6'),
	(76, 'tribute', 'n.贡物；献礼，贡献', '/‘tribju:t/', '6'),
	(77, 'trifle', 'n.小事，琐事；少许', '/‘traifl/', '6'),
	(78, 'trigger', 'n.扳机 vt.触发，引起', '/‘trigә/', '6'),
	(79, 'avail', 'vt.有益于 n.效用', '/ә’veil/', '6'),
	(80, 'trivial', 'a.琐碎的；平常的', '/‘triviәl/', '6'),
	(81, 'tuck', 'vt.折短，卷起；塞', '/tΛk/', '6'),
	(82, 'tug', 'vi.用力拖 n.猛拉，拖', '/tΛg/', '6'),
	(83, 'tuition', 'n.教，教诲；学费', '/tju:’iʃәn/', '6'),
	(84, 'tumble', 'vi.摔倒，跌倒；打滚', '/‘tΛmbl/', '6'),
	(85, 'turbulent', 'a.骚动的，骚乱的', '/‘tә:bjulәnt/', '6'),
	(86, 'turnover', 'n. 人员调整，营业额，成交量', '/‘tә:nouvә/', '6'),
	(87, 'tutor', 'vt.教，指导', '/‘tju:tә/', '6'),
	(88, 'ultraviolet', 'a.紫外的n.紫外线辐射', '/‘Λltrә’vaiәlit/', '6'),
	(89, 'unanimous', 'a.(全体)一致的', '/ju(:)’nænimәs/', '6'),
	(90, 'underestimate', 'vt.低估，看轻', '/Λndәr’estimeit/', '6'),
	(91, 'underlying', 'a. 在下的,含蓄的,潜在的', '/Λndә’laiiŋ/', '6'),
	(92, 'undermine', 'vt. 渐渐破坏,暗中破坏,侵蚀基础', '/Λndә’main/', '6'),
	(93, 'unemployment', 'n.失业；失业人数', '/‘Λnim’plɔimәnt/', '6'),
	(94, 'unfold', 'vt.展开 vi.呈现', '/Λn’fәuld/', '6'),
	(95, 'unify', 'vt. 统一,使成一体', '/‘ju:nifai/', '6'),
	(96, 'update', 'vt. 更新,使现代化', '/Λp’deit/', '6'),
	(97, 'upgrade', 'vt. 使升级,提升', '/‘Λp’greid/', '6'),
	(98, 'uphold', 'vt.举起；支撑；赞成', '/Λp’hәuld/', '6'),
	(99, 'validity', 'n.有效，效力；正确', '/vә’liditi/', '6'),
	(100, 'valve', 'n.阀，阀门；电子管', '/vælv/', '6'),
	(101, 'vegetation', 'n. 植物,草木', '/vedʒi’teiʃәn/', '6'),
	(102, 'veil', 'n.面纱，面罩；遮蔽物', '/veil/', '6'),
	(103, 'vein', 'n.静脉，血管，矿脉', '/vein/', '6'),
	(104, 'vent', 'n. 排放口,通风口 vt. 发泄,表达', '/vent/', '6'),
	(105, 'ventilate', 'vt.使通风，使换气', '/‘ventileit/', '6'),
	(106, 'verbal', 'a. 言辞的,文字的,口头的,动词的', '/‘vә:bәl/', '6'),
	(107, 'verdict', 'n. 裁决,结论,定论,判断', '/‘vә:dikt/', '6'),
	(108, 'verge', 'n.边缘，边界，界限', '/vә:dʒ/', '6'),
	(109, 'versatile', 'a.多方面的；通用的', '/‘vә:sәtail/', '6'),
	(110, 'verse', 'n.诗，韵文；诗行', '/vә:s/', '6'),
	(111, 'versus', 'prep.(比赛等中)对', '/‘vә:sәs/', '6'),
	(112, 'veto', 'n.否决，否决权，禁止', '/‘vi:tәu/', '6'),
	(113, 'vicinity', 'n.邻近；附近地区', '/vi’siniti/', '6'),
	(114, 'vicious', 'a.邪恶的；恶性的', '/‘viʃәs/', '6'),
	(115, 'violate', 'vt.违犯，违背；侵犯', '/‘vaiәleit/', '6'),
	(116, 'virgin', 'n.处女 a.处女的', '/‘vә:dʒin/', '6'),
	(117, 'virtual', 'a.实际上的，实质上的', '/‘vә:tjuәl/', '6'),
	(118, 'virus', 'n. 病毒', '/‘vaiәrәs/', '6'),
	(119, 'visualize', 'vt.使看得见/具体化,想象,设想', '/‘vizjuәlaiz/', '6'),
	(120, 'vocal', 'a. 直言不讳的，嗓音的,有声的', '/‘vәukәl/', '6'),
	(121, 'vocational', 'a. 职业的', '/vәu’keiʃәnl/', '6'),
	(122, 'void', 'a.空的；无效的', '/vɔid/', '6'),
	(123, 'volunteer', 'n.志愿者 vt.志愿', '/vɔlәn’tiә/', '6'),
	(124, 'vulgar', 'a.粗俗的，庸俗的', '/‘vΛlgә/', '6'),
	(125, 'vulnerable', 'a. 易受伤害/攻击的,脆弱的', '/‘vΛlnәrәbl/', '6'),
	(126, 'wallet', 'n.钱包，皮夹子', '/‘wɔlit/', '6'),
	(127, 'ward', 'n.病房，病室；监房', '/wɔ:d/', '6'),
	(128, 'warehouse', 'n.仓库，货栈', '/‘wɛәhaus/', '6'),
	(129, 'warfare', 'n.战争，战争状态', '/‘wɔ:fɛә/', '6'),
	(130, 'warrant', 'n. 正当理由, 委任状，许可证', '/‘wɔrәnt/', '6'),
	(131, 'watertight', 'a.不漏水的，防水的', '/‘wɔ:tәtait/', '6'),
	(132, 'watt', 'n.瓦(特)', '/wɔt/', '6'),
	(133, 'weary', 'a.疲倦的 vt.使疲乏', '/‘wiәri/', '6'),
	(134, 'web', 'n.网，丝，网状物', '/web/', '6'),
	(135, 'wedge', 'n.楔 vt.楔入；挤入', '/wedʒ/', '6'),
	(136, 'whereas', 'conj.而，却，反之', '/wɛәr’æz/', '6'),
	(137, 'whereby', 'ad.靠什么；靠那个', '/wɛә’bai/', '6'),
	(138, 'whirl', 'vt.使回旋 vi.&n.回旋', '/wә:l/', '6'),
	(139, 'withhold', 'vt. 拒绝，不给，使停止，阻挡', '/wið’hәuld/', '6'),
	(140, 'wrench', 'vt.拧，扭伤 n.拧', '/rentʃ/', '6'),
	(141, 'wretched', 'a.不幸的；卑鄙的', '/‘retʃid/', '6'),
	(142, 'wrinkle', 'n.皱纹 vt.使起皱纹', '/‘riŋkl/', '6'),
	(143, 'yacht', 'n.游艇，快艇', '/jɔt/', '6'),
	(144, 'yell', 'vi.叫喊', '/jel/', '6'),
	(145, 'yoke', 'n.轭，牛轭；枷锁', '/jәuk/', '6'),
	(146, 'base', 'n.基础，底层；基地', '/beis/', '4'),
	(147, 'basic', 'a.基本的，基础的', '/‘beisik/', '4'),
	(148, 'basically', 'ad.基本上', '/‘beisikəli/', '4'),
	(149, 'basin', 'n.盆，洗脸盆；盆地', '/‘beisn/', '4'),
	(150, 'basis', 'n.基础，根据', '/‘beisis/', '4'),
	(151, 'basket', 'n.篮，篓，筐', '/‘ba:skit/', '4'),
	(152, 'basketball', 'n.篮球；篮球运动', '/‘ba:skitbɔ:l/', '4'),
	(153, 'bath', 'n.浴，洗澡；浴缸', '/ba:θ/', '4'),
	(154, 'bathe', 'vt.给…洗澡；弄湿', '/beið/', '4'),
	(155, 'bathroom', 'n.浴室；盥洗室', '/‘ba:θrum/', '4'),
	(156, 'battery', 'n.电池；一套，一组', '/‘bætəri/', '4'),
	(157, 'battle', 'n.战役；斗争vi.作战', '/‘bætl/', '4'),
	(158, 'bay', 'n.湾；山脉中的凹处', '/bei/', '4'),
	(159, 'be', 'aux.v.&vi.是，在，做', '/bi:/', '4'),
	(160, 'beach', 'n.海滩，湖滩，河滩', '/bi:tʃ/', '4'),
	(161, 'beam', 'n.梁；横梁；束，柱', '/bi:m/', '4'),
	(162, 'bean', 'n.豆，蚕豆', '/bi:n/', '4'),
	(163, 'bear', 'n.熊；粗鲁的人', '/beə/', '4'),
	(164, 'bear', 'vt.容忍；负担；生育', '/beə/', '4'),
	(165, 'beard', 'n.胡须，络腮胡子', '/biəd/', '4'),
	(166, 'beast', 'n.兽，野兽；牲畜', '/bi:st/', '4'),
	(167, 'beat', 'vt.&vi.打，敲；打败', '/bi:t/', '4'),
	(168, 'beautiful', 'a.美的，美丽的', '/‘bju:tiful/', '4'),
	(169, 'beauty', 'n.美，美丽；美人', '/‘bju:ti/', '4'),
	(170, 'because', 'conj.由于，因为', '/bi’kɔz/', '4'),
	(171, 'become', 'vi.变成；成为，变得', '/bi’kΛm/', '4'),
	(172, 'bed', 'n.床，床位；圃；河床', '/bed/', '4'),
	(173, 'bee', 'n.蜂，密蜂；忙碌的人', '/bi:/', '4'),
	(174, 'beef', 'n.牛肉；菜牛', '/bi:f/', '4'),
	(175, 'beer', 'n.啤酒', '/biə/', '4'),
	(176, 'before', 'prep.在…以前；向…', '/bi’fɔ:/', '4'),
	(177, 'beg', 'vt.&vi.乞求；请求', '/beg/', '4'),
	(180, 'begin', 'vi.开始vt.开始', '/bi’gin/', '4'),
	(181, 'zinc', 'n.锌', '/ziŋk/', '6');

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
