-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.7.30-log - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             11.0.0.5919
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for words
CREATE DATABASE IF NOT EXISTS `fyptradtion` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `fyptradtion`;

-- Dumping data for table words.cet: ~4,447 rows (approximately)
/*!40000 ALTER TABLE `cet` DISABLE KEYS */;
INSERT IGNORE INTO `en_words` (`id`, `english`, `chinese`, `sent`, `level`) VALUES
	(1, '﻿abandon', 'vt.丢弃；放弃，抛弃', '/ə’bændən/', '4'),
	(2, 'pasture', 'n.牧场；牲畜饲养', '/‘pa:stʃә/', '6'),
	(3, 'patent', 'a.专利的 n.专利', '/‘peitәnt/', '6'),
	(4, 'pathetic', 'a.哀婉动人的；可怜的', '/pә’θetik/', '6'),
	(5, 'patriotic', 'a.爱国的', '/pætri’ɔtik/', '6'),
	(6, 'patrol', 'n.巡逻 n.巡逻，巡查', '/pә’trәul/', '6'),
	(7, 'pave', 'vt.铺，筑(路等)', '/peiv/', '6'),
	(8, 'pearl', 'n.珍珠；珍珠母', '/pә:l/', '6'),
	(9, 'pedal', 'n.踏脚，踏板，脚蹬', '/‘pedl/', '6'),
	(10, 'pedestrian', 'n.行人，步行者', '/pi’destriәn/', '6'),
	(11, 'peel', 'vt.剥(皮)，削(皮)', '/pi:l/', '6'),
	(12, 'peer', 'vi.凝视；隐约出现', '/piә/', '6'),
	(13, 'penalty', 'n.处罚，刑罚；罚款', '/‘penlti/', '6'),
	(14, 'pendulum', 'n.(钟等的)摆', '/‘pendjulәm/', '6'),
	(15, 'pension', 'n.抚恤金，年金', '/‘penʃәn/', '6'),
	(16, 'perception', 'n.感觉；概念；理解力', '/pә’sepʃәn/', '6'),
	(17, 'perfection', 'n.尽善尽美；无比精确', '/pә’fekʃәn/', '6'),
	(18, 'perfume', 'n.香味，芳香；香料', '/‘pә:fju:m, pә:’fju:m/', '6'),
	(19, 'periodic', 'n.周期的；一定时期的', '/‘piәri’ɔdik/', '6'),
	(20, 'periodical', 'n.期刊，杂志', '/piәri’ɔdikәl/', '6'),
	(21, 'perish', 'vi.死亡，夭折；枯萎', '/‘periʃ/', '6'),
	(22, 'permeate', 'vt. 弥漫,渗透,充满 vi. 透入', '/‘pә:miet/', '6'),
	(23, 'permissible', 'a. 可允许的', '/pә’misәbl/', '6'),
	(24, 'perpetual', 'a.永久的；四季开花的', '/pә’petʃuәl/', '6'),
	(25, 'perplex', 'vt.迷惑，困惑，难住', '/pә’pleks/', '6'),
	(26, 'persistent', 'a. 固执的,坚持的,持续的', '/pә(:)’sistәnt/', '6'),
	(27, 'pest', 'n.害虫；害人虫', '/pest/', '6'),
	(28, 'petition', 'n.请愿 vt.向…请愿', '/pi’tiʃәn/', '6'),
	(29, 'petty', 'a.细小的；器量小的', '/‘peti/', '6'),
	(30, 'physiological', 'a. 生理学的,生理学上的', '/fiziә’lɔdʒikәl/', '6'),
	(31, 'plague', 'n.瘟疫，鼠疫；天灾', '/pleig/', '6'),
	(32, 'plaster', 'n.灰泥；硬膏；熟石膏', '/‘pla:stә/', '6'),
	(33, 'plateau', 'n.高原；平稳时期', '/‘plætәu/', '6'),
	(34, 'plausible', 'a. 似乎真实的,似乎合理的', '/‘plɔ:zәbl/', '6'),
	(35, 'plea', 'n.请愿，请求，恳求', '/pli:/', '6'),
	(36, 'plead', 'vt.为…辩护 vi.抗辩', '/pli:d/', '6'),
	(37, 'pledge', 'n.誓言 vt.使发誓', '/pledʒ/', '6'),
	(38, 'poke', 'vt.戳，刺；伸(头等)', '/pәuk/', '6'),
	(39, 'polar', 'a.南(北)极的；极性的', '/‘pәulә/', '6'),
	(40, 'poll', 'n.投票 vi.投票', '/pәul/', '6'),
	(41, 'ponder', 'vt.考虑 vi.沉思', '/‘pɔndә/', '6'),
	(42, 'pope', 'n.(罗马天主教的)教皇', '/pәup/', '6'),
	(43, 'porch', 'n.门廊，入口处', '/pɔ:tʃ/', '6'),
	(44, 'pore', 'n.毛孔，气孔，细孔', '/pɔ:/', '6'),
	(45, 'portray', 'vt. 描绘,描写,描写...的肖像,', '/pɔ:’trei/', '6'),
	(46, 'pose', 'vi.假装，摆姿势 n.姿势', '/pәuz/', '6'),
	(47, 'poster', 'n. 海报,招贴,脚夫', '/‘pәustә/', '6'),
	(48, 'postulate', 'vt.要求，假定，假设', '/‘pɔstjuleit/', '6'),
	(49, 'practicable', 'a.能实行的；适用的', '/‘præktikәbl/', '6'),
	(50, 'prayer', 'n.祈祷，祈求', '/‘prɛә/', '6'),
	(51, 'preach', 'vt.说教，布道；鼓吹', '/pri:tʃ/', '6'),
	(52, 'precede', 'vt.先于… vi.领先', '/pri(:)’si:d/', '6'),
	(53, 'precipitate', 'a.突如其来的vt.使突然发生n.沉淀物', '/pri’sipiteit/', '6'),
	(54, 'preclude', 'vt. 预先排除,预防,阻止,妨碍', '/pri’klu:d/', '6'),
	(55, 'predecessor', 'n.前辈，前任者', '/‘pri:disesә/', '6'),
	(56, 'predominant', 'a.占优势的；主要的', '/pri’dɔminәnt/', '6'),
	(56, 'premature', 'a. 早熟/过早的 n. 早产儿', '/pri:mә’tjuә/', '6'),
	(57, 'premise', 'n. 前提,假设，房产', '/‘premis, pri’maiz/', '6'),
	(58, 'premium', 'n. 额外费用,奖金,奖赏,保险费', '/‘pri:mjәm/', '6'),
	(59, 'prescription', 'n.药方，处方的药', '/pris’kripʃәn/', '6'),
	(60, 'presentation', 'n.介绍；赠送；呈现', '/prezen’teiʃәn/', '6'),
	(61, 'preside', 'vi.主持；主奏', '/pri’zaid/', '6'),
	(62, 'prestige', 'n.威望，威信，声望', '/pres’ti:ʒ/', '6'),
	(63, 'presumably', 'ad.推测起来，大概', '/pri’zju:mәbli/', '6'),
	(64, 'presume', 'vt.假定，假设，揣测', '/pri’zju:m/', '6'),
	(65, 'pretext', 'n. 借口,托辞', '/‘pri:tekst/', '6'),
	(66, 'prevalent', 'a.流行的；盛行的', '/‘prevәlәnt/', '6'),
	(67, 'prey', 'vi.猎物 vi.捕获', '/prei/', '6'),
	(68, 'priest', 'n.教士，牧师，神父', '/pri:st/', '6'),
	(69, 'priority', 'n.先，前；优先，重点', '/prai’ɔriti/', '6'),
	(70, 'privacy', 'n. 隐私,隐居,秘密', '/‘praivәsi/', '6'),
	(71, 'probe', 'n.探针 vt.用探针探查', '/prәub/', '6'),
	(72, 'proceeding', 'n.程序，行动，事项', '/prә’si:diŋ/', '6'),
	(73, 'proclaim', 'vt.宣告，宣布；表明', '/prә’kleim/', '6'),
	(74, 'productive', 'a.生产的；出产…的', '/prә’dΛktiv/', '6'),
	(75, 'productivity', 'n.生产率；多产', '/prәdΛk’tiviti/', '6'),
	(76, 'proficiency', 'n.熟练，精通', '/prә’fiʃәnsi/', '6'),
	(77, 'profile', 'n. 侧面,轮廓,人物素描,传略', '/‘prәufail/', '6'),
	(78, 'profitable', 'a.有利的；有益的', '/‘prɔfitәbl/', '6'),
	(79, 'profound', 'a.深刻的；渊博的', '/prә’faund/', '6'),
	(80, 'prolong', 'vt.延长，拉长，拖延', '/prә’lɔŋ/', '6'),
	(81, 'promising', 'a.有希望的；有前途的', '/‘prɔmisiŋ/', '6'),
	(82, 'prone', 'a. 俯伏的,易于...的', '/prәun/', '6'),
	(83, 'propaganda', 'n.宣传；宣传机构', '/prɔpә’gændә/', '6'),
	(84, 'propagate', 'vt.繁殖；传播，普及', '/‘prɔpәgeit/', '6'),
	(85, 'propel', 'vt.推进，推动', '/prә’pel/', '6'),
	(86, 'prophet', 'n.预言家，先知', '/‘prɔfit/', '6'),
	(87, 'proposition', 'n.命题，主题；提议', '/prɔpә’ziʃәn/', '6'),
	(88, 'prose', 'n.散文', '/prәuz/', '6'),
	(89, 'prospective', 'a. 有希望的,预期/将来的', '/prәs’pektiv/', '6'),
	(90, 'prototype', 'n.原型；典型，范例', '/‘prәutәtaip/', '6'),
	(91, 'provocative', 'a. 挑衅的,刺激的,挑逗的', '/prә’vɔkәtiv/', '6'),
	(92, 'provoke', 'vt. 激怒,惹起,驱使', '/prә’vәuk/', '6'),
	(93, 'proximity', 'n. 接近,亲近', '/prak’simәti/', '6'),
	(94, 'publicity', 'n. 公开,名声,宣传', '/pΛb’lisiti/', '6'),
	(95, 'purify', 'vt.提纯，精炼(金属)', '/‘pjuәrifai/', '6'),
	(96, 'purity', 'n.纯净；纯洁；纯度', '/‘pjuәriti/', '6'),
	(97, 'pursuit', 'n.追赶；追求；事务', '/pә’sju:t/', '6'),
	(98, 'qualification', 'n.资格；限制条件', '/kwɔlifi’keiʃәn/', '6'),
	(99, 'qualitative', 'a.质的；定性的', '/‘kwɔlitәtiv/', '6'),
	(100, 'quantify', 'vt.确定…的数量', '/‘kwɔntifai/', '6'),
	(101, 'quantitative', 'a.量的；定量的', '/‘kwɔntitәtiv/', '6'),
	(102, 'quart', 'n.夸脱(=2品脱)', '/‘kwɔ:t/', '6'),
	(103, 'quarterly', 'a.季度的 ad.季度地', '/‘kwɔ:tәli/', '6'),
	(104, 'quartz', 'n.石英', '/kwɔ:ts/', '6'),
	(105, 'queer', 'a.奇怪的，古怪的', '/‘kwiә/', '6'),
	(106, 'quench', 'vt.熄灭，扑灭；压制', '/kwentʃ/', '6'),
	(107, 'quest', 'vt.寻找 vi.追求', '/kwest/', '6'),
	(108, 'questionnaire', 'n.调查表，征求意见表', '/kwestʃә’nɛә/', '6'),
	(109, 'quiver', 'vi.(轻微地)颤动', '/‘kwivә/', '6'),
	(110, 'racket', 'n.球拍', '/‘rækit/', '6'),
	(111, 'radiant', 'a.绚丽的；容光焕发的', '/‘reidjәnt/', '6'),
	(112, 'radiate', 'vi.发射光线；辐射', '/‘reidieit/', '6'),
	(113, 'radical', 'a.基本的；激进的', '/‘rædikәl/', '6'),
	(114, 'rage', 'n.(一阵)狂怒，盛怒', '/reidʒ/', '6'),
	(115, 'raid', 'n.袭击；突然搜查', '/reid/', '6'),
	(116, 'rally', 'n.&vt.&vi.(重新)集合', '/‘ræli/', '6'),
	(117, 'random', 'n.随机 a.随机的', '/‘rændәm/', '6'),
	(118, 'rating', 'n. 等级,评定结果，收视(听)率', '/‘reitiŋ/', '6'),
	(119, 'readily', 'ad.乐意地；无困难地', '/‘redili/', '6'),
	(120, 'realistic', 'a.现实的；现实主义的', '/riә’listik/', '6'),
	(121, 'reap', 'vt.&vi.收割，收获', '/ri:p/', '6'),
	(122, 'rebellion', 'n.造反；叛乱；反抗', '/ri’beljәn/', '6'),
	(123, 'recession', 'n. (经济)衰退,不景气', '/ri’seʃәn/', '6'),
	(124, 'recipe', 'n. 菜谱，烹饪法；处方', '/‘resipi/', '6'),
	(125, 'recipient', 'n. 接受者，接收者', '/ri’sipiәnt/', '6'),
	(126, 'reciprocal', 'a.相互的；互利的', '/ri’siprәkәl/', '6'),
	(127, 'recite', 'vt.&vi.背诵，朗诵', '/ri’sait/', '6'),
	(128, 'reckless', 'a.粗心大意的；鲁莽的', '/‘reklis/', '6'),
	(129, 'reckon', 'vi.数，算帐 vt.认为', '/‘rekәn/', '6'),
	(130, 'reclaim', 'vt.开垦，开拓；回收', '/ri’kleim/', '6'),
	(131, 'reconcile', 'vt.使和好；调停', '/‘rekәnsail/', '6'),
	(132, 'recreation', 'n.消遣，娱乐活动', '/rekri’eiʃәn/', '6'),
	(133, 'recruit', 'vi.征募(新兵),招收 n. 新兵,新成员', '/ri’kru:t/', '6'),
	(134, 'rectangular', 'a. 矩形的,成直角的', '/rek’tæŋgjulә/', '6'),
	(135, 'rectify', 'vt.纠正；调整；精馏', '/‘rektifai/', '6'),
	(136, 'recur', 'vi. 复发,重现,再发生', '/ri’kә:/', '6'),
	(137, 'recycle', 'vt. 使再循环,再利用,再制', '/‘ri:’saikl/', '6'),
	(138, 'redundant', 'a. 多余的,过多的,冗长的', '/ri’dΛndәnt/', '6'),
	(139, 'refrain', 'vi.抑制，制止，忍住', '/ri’frein/', '6'),
	(140, 'refreshment', 'n.茶点，点心，便餐', '/ri’freʃmәnt/', '6'),
	(141, 'baggage', 'n.行李', '/‘bægidʒ/', '4'),
	(142, 'bake', 'vt.烤，烘，焙；烧硬', '/beik/', '4'),
	(143, 'balance', 'vt.使平衡；称n.天平', '/‘bæləns/', '4'),
	(144, 'ball', 'n.球，球状物；舞会', '/bɔ:l/', '4'),
	(145, 'balloon', 'n.气球，玩具气球', '/bə’lu:n/', '4'),
	(146, 'banana', 'n.香蕉；芭蕉属植物', '/bə’na:nə/', '4'),
	(147, 'band', 'n.乐队；带；波段', '/bænd/', '4'),
	(148, 'bang', 'n.巨响，枪声；猛击', '/bæŋ/', '4'),
	(149, 'bank', 'n.银行；库；岩，堤', '/bæŋk/', '4'),
	(150, 'bar', 'n.酒吧间；条，杆；栅', '/ba:/', '4'),
	(151, 'refugee', 'n.难民，流亡者', '/refju:’dʒi:/', '6'),
	(152, 'barber', 'n.理发师', '/‘ba:bə/', '4'),
	(153, 'bare', 'a.赤裸的；仅仅的', '/beə/', '4'),
	(154, 'bargain', 'n.交易vi.议价；成交', '/‘ba:gin/', '4'),
	(155, 'barrel', 'n.桶；圆筒；枪管', '/‘bærəl/', '4'),
	(156, 'barrier', 'n.栅栏，屏障；障碍', '/‘bæriə/', '4'),
	(157, 'base', 'n.基础，底层；基地', '/beis/', '4'),
	(158, 'basic', 'a.基本的，基础的', '/‘beisik/', '4'),
	(159, 'basically', 'ad.基本上', '/‘beisikəli/', '4'),
	(160, 'basin', 'n.盆，洗脸盆；盆地', '/‘beisn/', '4'),
	(161, 'basis', 'n.基础，根据', '/‘beisis/', '4'),
	(162, 'basket', 'n.篮，篓，筐', '/‘ba:skit/', '4'),
	(163, 'basketball', 'n.篮球；篮球运动', '/‘ba:skitbɔ:l/', '4'),
	(164, 'bath', 'n.浴，洗澡；浴缸', '/ba:θ/', '4'),
	(165, 'bathe', 'vt.给…洗澡；弄湿', '/beið/', '4'),
	(166, 'bathroom', 'n.浴室；盥洗室', '/‘ba:θrum/', '4'),
	(167, 'battery', 'n.电池；一套，一组', '/‘bætəri/', '4'),
	(168, 'battle', 'n.战役；斗争vi.作战', '/‘bætl/', '4'),
	(169, 'bay', 'n.湾；山脉中的凹处', '/bei/', '4'),
	(170, 'be', 'aux.v.&vi.是，在，做', '/bi:/', '4'),
	(171, 'beach', 'n.海滩，湖滩，河滩', '/bi:tʃ/', '4'),
	(172, 'beam', 'n.梁；横梁；束，柱', '/bi:m/', '4'),
	(173, 'bean', 'n.豆，蚕豆', '/bi:n/', '4'),
	(174, 'bear', 'n.熊；粗鲁的人', '/beə/', '4'),
	(175, 'bear', 'vt.容忍；负担；生育', '/beə/', '4'),
	(176, 'beard', 'n.胡须，络腮胡子', '/biəd/', '4'),
	(177, 'beast', 'n.兽，野兽；牲畜', '/bi:st/', '4'),
	(178, 'beat', 'vt.&vi.打，敲；打败', '/bi:t/', '4'),
	(179, 'beautiful', 'a.美的，美丽的', '/‘bju:tiful/', '4'),
	(180, 'beauty', 'n.美，美丽；美人', '/‘bju:ti/', '4'),
	(181, 'because', 'conj.由于，因为', '/bi’kɔz/', '4'),
	(182, 'become', 'vi.变成；成为，变得', '/bi’kΛm/', '4'),
	(183, 'bed', 'n.床，床位；圃；河床', '/bed/', '4'),
	(184, 'bee', 'n.蜂，密蜂；忙碌的人', '/bi:/', '4'),
	(185, 'beef', 'n.牛肉；菜牛', '/bi:f/', '4'),
	(186, 'beer', 'n.啤酒', '/biə/', '4'),
	(187, 'before', 'prep.在…以前；向…', '/bi’fɔ:/', '4'),
	(188, 'beg', 'vt.&vi.乞求；请求', '/beg/', '4'),
	(189, 'begin', 'vi.开始vt.开始', '/bi’gin/', '4'),
	(190, 'beginning', 'n.开始，开端；起源', '/bi’giniŋ/', '4'),
	(191, 'behalf', 'n.利益，维护，支持', '/bi’ha:f/', '4'),
	(192, 'behave', 'vi.表现，举止；运转', '/bi’heiv/', '4'),
	(193, 'behavior', 'n.行为，举止，态度', '/bi’heivjə/', '4'),
	(194, 'behind', 'prep.在…后面', '/bi’haind/', '4'),
	(195, 'being', 'n.存在；生物；生命', '/‘bi:iŋ/', '4'),
	(196, 'belief', 'n.信任，相信；信念', '/bi’li:f/', '4'),
	(197, 'believe', 'vt.相信；认为', '/bi’li:v/', '4'),
	(198, 'bell', 'n.钟，铃，门铃；钟声', '/bel/', '4'),
	(199, 'belong', 'vi.属于，附属', '/bi’lɔŋ/', '4'),
	(200, 'below', 'prep.在…下面(以下)', '/bi’ləu/', '4'),
	(201, 'yoke', 'n.轭，牛轭；枷锁', '/jәuk/', '6'),
	(202, 'youngster', 'n.儿童，少年，年轻人', '/‘jΛŋstә/', '6'),
	(203, 'zinc', 'n.锌', '/ziŋk/', '6');

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
